GEMINI_API_KEY = "AIzaSyCDh3PgVWUlmyg0sB4QNPU1Hk3JViea1mU"
# Esto es para conectar con Google Sheets
# Copia y pega el contenido de tu archivo .json aquí
[gcp_service_account]
type = "service_account"
project_id = "ai-commissions-chatbot"
private_key_id = "xxxxxxxxxxxxxxxxxxxx"
private_key = "-----BEGIN PRIVATE KEY-----\nxxxxxxxxxx\n-----END PRIVATE KEY-----\n"
client_email = "chatbot-sheets-writer@ai-commissions-chatbot.iam.gserviceaccount.com"
client_id = "1234567890"
auth_uri = "https-accounts-google-com-o-oauth2-auth"
token_uri = "https-oauth2-googleapis-com-token"
auth_provider_x509_cert_url = "https-www-googleapis-com-oauth2-v1-certs"
client_x509_cert_url = "https-www-googleapis-com-robot-v1-metadata-x509-chatbot-sheets-writer%40ai-commissions-chatbot.iam.gserviceaccount.com"
universe_domain = "googleapis.com"